# Generated by Django 5.1.4 on 2026-04-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="busassignment",
            name="conductor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "conductor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
